name: Build debian packages

on: [push, pull_request]

jobs:
  build_debs:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS_FILE: https://raw.githubusercontent.com/reinzor/ros_debian_packages/main/packages.repos
